version: '3'

services:
  htlink:
    image: leu3ery/htlink-backend:latest
    volumes:
      - htlink-public-data:/app/public
    environment:
      PORT: 3000
      JWT_SECRET: ${JWT_SECRET_COMPOSE}
      MONGO_URI: ${MONGO_URI_COMPOSE}
      PASSWORD_SALT: ${PASSWORD_SALT}
      DOMEN: ${DOMEN}
      LDAP_URL: ${LDAP_URL}
      LDAP_BIND_DN: ${LDAP_BIND_DN}
      LDAP_BIND_PW: ${LDAP_BIND_PW}
      LDAP_SEARCH_BASES: ${LDAP_SEARCH_BASES}
    depends_on:
      - mongodb

  client:
    image: leu3ery/htlink-frontend:latest
    ports:
      - "${PORT}:80"
    depends_on:
      - htlink

  tailscale:
    image: tailscale/tailscale:latest
    hostname: htlink-mongo
    environment:
      TS_AUTHKEY: ${TS_AUTH}
      TS_STATE_DIR: /var/lib/tailscale
      TS_USERSPACE: "true"
    volumes:
      - tailscale_state:/var/lib/tailscale
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped

  mongodb:
    image: mongodb/mongodb-community-server:latest
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
  htlink-public-data:
  tailscale_state:
  