version: '3'
services:
  htlink:
    image: leu3ery/htlink-backend:latest
    # restart: always
    ports: 
      - "${PORT}:${PORT}"
    volumes:
      - htlink-public-data:/app/public
    environment: 
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET_COMPOSE}
      MONGO_URI: ${MONGO_URI_COMPOSE}
      PASSWORD_SALT: ${PASSWORD_SALT}
      DOMEN: ${DOMEN}
    depends_on:
      - mongodb
  mongodb:
    image: mongodb/mongodb-community-server:latest
    # restart: always
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
  htlink-public-data:
  