version: '3'

services:
  htlink:
    image: leu3ery/htlink-backend:latest
    volumes:
      - htlink-public-data:/app/public
    environment:
      PORT: 3000
      JWT_SECRET: ${JWT_SECRET_COMPOSE}
      MONGO_URI: ${MONGO_URI_COMPOSE}
      PASSWORD_SALT: ${PASSWORD_SALT}
      DOMEN: ${DOMEN}
    depends_on:
      - mongodb

  client:
    image: leu3ery/htlink-frontend:latest
    volumes:
      - client-dist:/dist
    depends_on:
      - htlink

  nginx:
    image: nginx:1.27-alpine
    ports:
      - "${PORT}:80"
    volumes:
      - client-dist:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - client
      - htlink
      - mongodb

  mongodb:
    image: mongodb/mongodb-community-server:latest
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
  htlink-public-data:
  client-dist:
  