version: '3'

services:
  htlink:
    image: leu3ery/htlink-backend:latest
    volumes:
      - htlink-public-data:/app/public
    environment:
      PORT: 3000
      JWT_SECRET: ${JWT_SECRET_COMPOSE}
      MONGO_URI: ${MONGO_URI_COMPOSE}
      PASSWORD_SALT: ${PASSWORD_SALT}
      DOMEN: ${DOMEN}
      LDAP_URL: ${LDAP_URL}
      LDAP_BIND_DN: ${LDAP_BIND_DN}
      LDAP_BIND_PW: ${LDAP_BIND_PW}
      LDAP_SEARCH_BASES: ${LDAP_SEARCH_BASES}
    depends_on:
      - mongodb

  client:
    image: leu3ery/htlink-frontend:latest
    ports:
      - "${PORT}:80"
    depends_on:
      - htlink

  mongo:
    image: mongodb/mongodb-community-server:latest
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb-data:/data/db
  mongo-admin:
      image: mongo-express:latest
      ports:
        - "8081:8081"
      depends_on:
        - mongo
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        ME_CONFIG_MONGODB_SERVER: mongo


volumes:
  mongodb-data:
  htlink-public-data:
