version: "3"

services:
  htlink:
    image: leu3ery/htlink-backend:latest
    volumes:
      - htlink-public-data:/app/public
    environment:
      PORT: 3000
      JWT_SECRET: ${JWT_SECRET_COMPOSE}
      MONGO_URI: ${MONGO_URI_COMPOSE}
      PASSWORD_SALT: ${PASSWORD_SALT}
      DOMEN: ${DOMEN}
      LDAP_URL: ${LDAP_URL}
      LDAP_BIND_DN: ${LDAP_BIND_DN}
      LDAP_BIND_PW: ${LDAP_BIND_PW}
      LDAP_SEARCH_BASES: ${LDAP_SEARCH_BASES}
    depends_on:
      mongodb:
            condition: service_healthy

  client:
    image: leu3ery/htlink-frontend:latest
    ports:
      - "${PORT}:80"
    depends_on:
      - htlink

  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb-data:/data/db
    healthcheck:
      test: [ "CMD-SHELL", "mongosh --quiet -u $$MONGO_INITDB_ROOT_USERNAME -p $$MONGO_INITDB_ROOT_PASSWORD --authenticationDatabase admin --eval 'db.adminCommand({ ping: 1 }).ok' | grep 1" ]
      interval: 5s
      timeout: 5s
      retries: 20


volumes:
  mongodb-data:
  htlink-public-data: